#!/bin/bash

function build_gtest()
{
    mkdir -p ./build/gtest
    cd ./build/gtest
    cmake -DBUILD_SHARED_LIBS=ON ../../vendor/gtest
    make all
    cd ../../
}

function build_sfml()
{
    mkdir -p ./build/sfml
    cd ./build/sfml
    cmake -DBUILD_SHARED_LIBS=ON ../../vendor/sfml
    make all
    cd ../../
}

function build_vendor()
{
    build_gtest
    build_sfml
}

function build_sources()
{
    mkdir -p ./build
    cd ./build
    cmake ..
    make tests
    ../bin/tests
    if [[ $? -eq 0 ]]; then
    	make all
    fi
    cd ../
}

function run()
{
    build_vendor
    build_sources

    ./bin/game
}

function test()
{
    build_vendor

    mkdir -p ./build
    cd ./build
    cmake ..
    make tests
    ../bin/tests
}

function build_all()
{
    build_vendor
    build_sources
}

function clean()
{
    rm bin/game bin/tests bin/lib/libclasses*
    rm -R build/*
}

MODE=$1
if [[ ${MODE} == "build" ]]; then
    build_all
elif [[ ${MODE} == "run" ]]; then
    run
elif [[ ${MODE} == "test" ]]; then
    test
elif [[ ${MODE} == "clean" ]]; then
    clean
else
    echo -e "The Mario::Edit CLI \xF0\x9F\x92\xAA"
    echo -e "Usage: $0 COMMAND"
    echo -e ""
    echo -e "List of available commands:"
    echo "  build     - builds all sources"
    echo "  run       - runs game"
    echo "  test      - runs tests"
    echo "  clean     - does cleaning"
fi